vars:
  registry: docker-registry.dun.fh
  service_name: vaultex

tasks:
  build:
    - cmd: docker build --force-rm -t <%=registry%>/findmypast/<%=service_name%>:<%=version%> .

  push:
    - cmd: docker push <%=registry%>/findmypast/<%=service_name%>:<%=version%>

  # Run unit tests inside a container
  test:
    - cmd: docker run --name vaultex-test-runner --rm <%=registry%>/findmypast/<%=service_name%>:<%=version%> mix test

  # Publish to Hex Repository
  publish:
    - cmd: docker run -e HEX_USER -e HEX_PASSWORD --name vaultex-publisher --rm <%=registry%>/findmypast/<%=service_name%>:<%=version%> sh -c "mix hex.user auth && mix hex publish"
      environment:
        - HEX_USER=<%=user%>
        - HEX_PASSWORD=<%=password%>
