vars:
  service_name: vaultex
  image: docker-registry.dun.fh/findmypast/<%=service_name%>:<%=version%>

tasks:
  build:
    - cmd: docker build --force-rm --build-arg MIX_ENV=<%=mix_env%> -t <%=image%> .

  push:
    - cmd: docker push <%=image%>

  # Run unit tests inside a container
  test:
    - cmd: docker-compose -f docker-compose/test.yml build test
    - cmd: docker-compose -f docker-compose/test.yml run test

  # Publish to Hex Repository
  publish:
    - cmd: docker run -e HEX_USER -e HEX_PASSWORD --name vaultex-publish --rm <%=image%> sh -c "mix hex.user auth && mix hex publish"
      environment:
        - HEX_USER=<%=user%>
        - HEX_PASSWORD=<%=password%>
